services:
  master:
    build: .
    container_name: rpc_master
    entrypoint: ["bash", "./start.sh"]
    volumes:
      - type: bind
        source: ./src
        target: /app/src
  worker:
    build: .
    container_name: rpc_worker
    entrypoint: ["bash", "./start.sh"]
    volumes:
      - type: bind
        source: ./src
        target: /app/src