services:
  master:
    build: .
    container_name: rpc_master
    security_opt:
      - seccomp:unconfined
    # entrypoint: ["bash", "./start.sh"]
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    cap_add:
      - SYS_PTRACE
  worker:
    build: .
    container_name: rpc_worker
    security_opt:
      - seccomp:unconfined
    # entrypoint: ["bash", "./start.sh"]
    volumes:
      - type: bind
        source: ./src
        target: /app/src