services:
  master:
    build: .
    container_name: rpc_master
    network_mode: bridge
    security_opt:
      - seccomp:unconfined
    # entrypoint: ["bash", "./start.sh"]
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    cap_add:
      - SYS_PTRACE
    ports:
      - "5000:5000"
  worker:
    build: .
    container_name: rpc_worker
    network_mode: bridge
    security_opt:
      - seccomp:unconfined
    # entrypoint: ["bash", "./start.sh"]
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    cap_add:
      - SYS_PTRACE
    ports:
      - "5001:5000"