/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "rpc.h"
#define TAM_WORDS 654633

void
prog_100(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * words_freq_100_arg;
	char * *result_2;
	char * words_length_100_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = words_freq_100(&words_freq_100_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = words_length_100(&words_length_100_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

char *word_freq(CLIENT *clnt, char *request){
	char **response;

	response = words_freq_100(&request, clnt);
	if (response == NULL){
		fprintf(stderr, "Problema na chamada RPC\n");
		exit(0);
	}

	return (*response);
}

char *word_tam(CLIENT *clnt, char *request){
	char **response;

	response = words_length_100(&request, clnt);
	if (response == NULL){
		fprintf(stderr, "Problema na chamada RPC\n");
		exit(0);
	}

	return (*response);
}

int main (int argc, char *argv[])
{
	CLIENT *clnt;
	FILE *arq;
	char text[TAM_WORDS];
  char buffer[TAM_WORDS];
  int buffertTam;

	char *worker_ip;
	char *path;
	
	worker_ip = argv[1];
	path = argv[2];

	if (argc < 3) {
		fprintf (stderr, "Uso: %s worker_ip file_path\n", argv[0]);
		exit (1);
	}

	clnt = clnt_create(worker_ip, PROG, VERSAO, "udp");

	if (clnt == (CLIENT *) NULL){
		clnt_pcreateerror(worker_ip);
		exit(1);
	}


	// Abre o arquivo example.txt
  arq = fopen(path, "r");
  if (arq == NULL) {
    printf("Erro na abertura de arquivo!\n");
    return 1;
  }
  
  // pega o tamanho máximo
  buffertTam = fread(buffer, 1, TAM_WORDS, arq);

  if (buffertTam == 0) {
    printf("Arquivo vazio!\n");
    return 0;
  }

  // percorre todo o arquivo
  int index = 0;
  for (int i = 0; i <= buffertTam; i++) {
    if ((buffer[i] >= 65 && buffer[i] <= 90) ||
        (buffer[i] >= 97 && buffer[i] <= 122) ||
        (buffer[i] == 32 && i < buffertTam)) {
      text[index++] = buffer[i];
    }
  }

	printf("%s\n", word_freq(clnt, text));
	printf("%s\n", word_tam(clnt, text));
	
	return 0;
}
